
# jansson Source Files
JANSSON_SRC_FILES := \
    $(JANSSON_SRC)/dump.c \
    $(JANSSON_SRC)/error.c \
    $(JANSSON_SRC)/hashtable.c \
    $(JANSSON_SRC)/hashtable_seed.c \
    $(JANSSON_SRC)/load.c \
    $(JANSSON_SRC)/memory.c \
    $(JANSSON_SRC)/pack_unpack.c \
    $(JANSSON_SRC)/strbuffer.c \
    $(JANSSON_SRC)/strconv.c \
    $(JANSSON_SRC)/utf.c \
    $(JANSSON_SRC)/value.c \
