
JNI_CORE_SRC_FILES := \
    $(JNI_CORE_SRC)/AsyncOperationImpl.cpp \
    $(JNI_CORE_SRC)/CanExecuteChangedEventArgs.cpp \
    $(JNI_CORE_SRC)/ObservableCollectionImpl.cpp \
    $(JNI_CORE_SRC)/CompletedEventArgs.cpp \
    $(JNI_CORE_SRC)/CommandImpl.cpp \
    $(JNI_CORE_SRC)/Dictionary.cpp \
    $(JNI_CORE_SRC)/Dispatcher.cpp \
    $(JNI_CORE_SRC)/EventModelEventArgs.cpp \
    $(JNI_CORE_SRC)/FactoryObject.cpp \
    $(JNI_CORE_SRC)/FoundationObjectImpl.cpp \
    $(JNI_CORE_SRC)/InspectableObject.cpp \
    $(JNI_CORE_SRC)/ObservableListImpl.cpp \
    $(JNI_CORE_SRC)/Logger.cpp \
    $(JNI_CORE_SRC)/NotifyCollectionChangedEventArgs.cpp \
    $(JNI_CORE_SRC)/ObjectFactoryImpl.cpp \
    $(JNI_CORE_SRC)/ObjectTypeInfo.cpp \
    $(JNI_CORE_SRC)/PropertyChangedEventArgs.cpp \
    $(JNI_CORE_SRC)/PropertyInfoImpl.cpp \
    $(JNI_CORE_SRC)/ObservableObjectImpl.cpp \
    $(JNI_CORE_SRC)/ObservableObjectInfoImpl.cpp \
    $(JNI_CORE_SRC)/PropertyTypeInfoImpl.cpp \
    $(JNI_CORE_SRC)/PropertyValueImpl.cpp \
    $(JNI_CORE_SRC)/JniCoreUtils.cpp \
    $(JNI_CORE_SRC)/JniLoadLibrary.cpp \
    $(JNI_CORE_SRC)/JniUtility.cpp \
    $(JNI_CORE_SRC)/JObject.cpp \
    $(JNI_CORE_SRC)/JClass.cpp \
    $(JNI_CORE_SRC)/JString.cpp \
    $(JNI_CORE_SRC)/JVMEnv.cpp \
    $(JNI_CORE_SRC)/JsonUtil.cpp \

