
# PInvoke Source Files
PINVOKE_SRC_FILES := \
    $(PINVOKE_SRC)/PInvokeUtils.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeActivationFactory.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeAsyncOperation.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeDictionary.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeDispatcherAdapter.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeEnumValue.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeEnumerable.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeInspectable.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeLogger.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeObject.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeObjectTypeInfo.cpp \
    $(PINVOKE_SRC)/foundation/PInvokePropertyValue.cpp \
    $(PINVOKE_SRC)/foundation/PInvokeObjectDispatch.cpp \
    $(PINVOKE_SRC)/foundation/PInvokePropertyTypeInfo.cpp \
    $(PINVOKE_SRC)/model/PInvokeObjectStaticsUtil.cpp \
    $(PINVOKE_SRC)/model/PInvokeCommand.cpp \
    $(PINVOKE_SRC)/model/PInvokeObservableCollection.cpp \
    $(PINVOKE_SRC)/model/PInvokeObservableObject.cpp \
